services:
  back-end:
    build: 
      context: ./backend
    container_name: back-end
    working_dir: /app
    networks:
      - node-network
    volumes:
      - ./backend:/app
      - /app/node_modules
    tty: true
    ports:
      - "3000:3000"
    command: npm run start

  front-end:
    build: 
      context: ./front-app
    container_name: front-end
    working_dir: /app
    networks:
      - node-network
    volumes: 
      - ./front-app:/app
      - /app/node_modules
    tty: true
    ports: 
      - "5173:5173"
    command: npm run dev

networks:
  node-network: 
    